# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sentiment.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'sentiment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fsentiment.proto\x12\tsentiment\"\x1b\n\x0bTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"5\n\x11SentimentResponse\x12\x11\n\tsentiment\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\x32X\n\x11SentimentAnalyzer\x12\x43\n\x0b\x41nalyzeText\x12\x16.sentiment.TextRequest\x1a\x1c.sentiment.SentimentResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sentiment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEXTREQUEST']._serialized_start=30
  _globals['_TEXTREQUEST']._serialized_end=57
  _globals['_SENTIMENTRESPONSE']._serialized_start=59
  _globals['_SENTIMENTRESPONSE']._serialized_end=112
  _globals['_SENTIMENTANALYZER']._serialized_start=114
  _globals['_SENTIMENTANALYZER']._serialized_end=202
# @@protoc_insertion_point(module_scope)
